# Generated by Django 4.2.7 on 2023-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="created_by",
            field=models.CharField(max_length=255, verbose_name="Создатель"),
        ),
    ]
