# Generated by Django 4.2.7 on 2023-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_taskmodel_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmodel",
            name="employee_comment",
        ),
        migrations.AddField(
            model_name="employeemodel",
            name="employee_comment",
            field=models.TextField(null=True, verbose_name="Комментарий работника"),
        ),
    ]
