# Generated by Django 4.2.7 on 2024-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_employeetaskmodel_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminmodel",
            name="patronymic",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="employeetaskmodel",
            name="employee_comment",
            field=models.TextField(
                blank=True,
                default="нет комментария",
                null=True,
                verbose_name="Комментарий работника",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="type_of_task",
            field=models.CharField(
                choices=[
                    ("batch_production", "Производство"),
                    ("testing", "Тестирование"),
                    ("repair", "Ремонт"),
                    ("shipments", "Отгрузка"),
                    ("other", "Прочее"),
                ],
                max_length=255,
                verbose_name="Тип работы",
            ),
        ),
    ]
