# Generated by Django 4.2.7 on 2024-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_adminmodel_patronymic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="patronymic",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Отчество",
            ),
        ),
    ]
