# Generated by Django 4.2.7 on 2024-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employeemodel_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetaskmodel',
            name='employee_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий работника'),
        ),
    ]
