# Generated by Django 4.2.7 on 2024-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employeetaskmodel_employee_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
    ]
